### ISSUE TITLE
[PLAN] Chọn mã nguồn CMS

### ISSUE THREAD

**Issue by khanhicetea** [K11-FOSS-L2/L2-AIMABIET-FINALPROJ#2]
Đề tài khá rộng trong việc chọn CMS. Mà mình thấy nó gần là 1 trang eCommerce hơn nên cũng có 1 số cân nhắc nên sử dụng OpenCart ( kiến trúc MVC đẹp - rõ ràng hơn ) thay vì Wordpress hoặc Drupal. Các bạn cho ý kiến về việc chọn mã nguồn nhé.

1. OpenCart
2. Wordpress
3. Drupal

Tổng kết bình chọn vào ngày 08/04/2015.

**Comment by kingmax123** [comment]
thấy wordpress thông dụng hơn nên nghĩ sẽ được support nhiều hơn nếu bí cái gì đó.

**Comment by khanhicetea** [comment]
Yêu cầu plugin cũng đơn giản nên cũng không có gì để bí đâu chú :smiley:
Thế chú vote Wordpress phải không ?

**Comment by 1112360** [comment]
Em bắt cái OpenCart vậy.

**Comment by 1112439** [comment]
Wordpress đi mấy chú

**Comment by khanhicetea** [comment]
Mấy chú qua repo mới của ông thầy tạo nhé https://github.com/HCMUS-OSSD/L2_AIMABIET
