### ISSUE TITLE
[Không liên quan] Nên dùng cái linux nào đây mấy chú

### ISSUE THREAD

**Issue by 1112360** [K11-FOSS-L2/L2-AIMABIET-FINALPROJ#3]
1. Ubuntu mới nhất chậm quá
2. Fedora 21 yum update bug tum2 lum
3. Em không thích RedHat

p/s : chú Khanh đang xài cái nào phiên bản may16ie6, chỉ em đang cần chạy cái Hadoop/Hive

**Comment by khanhicetea** [comment]
Ubuntu 14.04.2 LTS đi chú.

**Comment by 1112360** [comment]
ok, thanks
