### ISSUE TITLE
Joking or something

### ISSUE THREAD

**Issue by 1112360** [K11-FOSS-L2/L2-AIMABIET-FINALPROJ#4]
404 on HCMUS-OSSD/L2_AIMABIET

**Comment by khanhicetea** [comment]
Chu vao mail co thu invite vao Team do

**Comment by 1112360** [comment]
thấy gi2d9a6u trời

**Comment by khanhicetea** [comment]
Check lai di chu'

**Comment by 1112360** [comment]
ro62i giờ thi2tha61y rồi

**Comment by 1112360** [comment]
vậy h cái git này làm sao

**Comment by khanhicetea** [comment]
T sap delete cai repo nay roi, chuyen qa repo moi ma lam viec.

**Comment by 1112360** [comment]
ok
